eventFinderApp/urls.py
from django.urls import path

from . import views


app_name = 'eventFinderApp'

urlpatterns = [
    # event-finder/
    path('', views.IndexView.as_view(), name='index'),
    # event-finder/1
    path('<int:pk>/', views.EventView.as_view(), name='event'),
    # event-finder/my-account
    path('my-account/', views.account, name='account')
]

eventFinderProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('event-finder/', include('eventFinderApp.urls')),
    path('admin/', admin.site.urls),
]

eventFinderApp/models.py
from django.db import models


class Event(models.Model):
    title = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    start_time = models.DateTimeField('start time and date')
    end_time = models.DateTimeField('end time and date')


class Category(models.Model):
    name = models.CharField(max_length=50)

eventFinderApp/views.py
from django.http import HttpResponse
from django.views import generic
from django.shortcuts import render
from .models import Event


class IndexView(generic.ListView):
    template_name = 'eventFinderApp/index.html'
    context_object_name = 'events_list'

    def get_queryset(self):
        '''Return the events.'''
        return Event.objects.all()


class EventView(generic.DetailView):
    model = Event
    template_name = 'eventFinderApp/event.html'


def account(request):
    return render(request, 'eventFinderApp/account.html')

eventFinderApp/templates/eventFinderApp/account.html
{% extends "./base.html" %}

{% block content %}

You should put the user's account information and upcoming events here.

{% endblock %}

eventFinderApp/templates/eventFinderApp/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>EventFinda</title>
        <meta name="description" content="">
        <meta name="author" content="Hayley van Waas">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'eventFinderApp/style.css' %}">
    </head>

    <body>
        <header>
            <div>
                <h1>EventFinda</h1>
                <h2>Find free events near you!</h2>
            </div>
            {% include './nav.html' %}
        </header>

        {% block content %}{% endblock %}
    </body>
</html>

eventFinderApp/templates/eventFinderApp/detailsBox.html
<div class="details-box">
    <a href="{% url 'eventFinderApp:event' event.id %}">
        <p>{{ event.title }}</p>
        <p>{{ event.start_time }}</p>
    </a>
</div>

eventFinderApp/templates/eventFinderApp/event.html
{% extends "./base.html" %}

{% block content %}

<h2>{{ event.title }}</h2>

<p>{{ event.location }}</p>
<p>Starts at: {{ event.start_time }}</p>
<p>Ends at: {{ event.end_time }}</p>

{% endblock %}

eventFinderApp/templates/eventFinderApp/index.html
{% extends "./base.html" %}

{% block content %}

    <button id="new-event">+ Create new event</button>
    <h3>See what's on!</h3>
    {% if events_list %}
        {% for event in events_list %}
            {% include "./detailsBox.html" with event=event %}
        {% endfor %}
    {% else %}
        <p>No events are available.</p>
    {% endif %}

{% endblock %}

eventFinderApp/templates/eventFinderApp/nav.html
<nav>
    <a href="{% url 'eventFinderApp:index' %}">Home</a>
    <a href="{% url 'eventFinderApp:account' %}">My Account</a>
</nav>